### ISSUE TITLE
pipelines for singularity hub

### ISSUE THREAD

**Issue by vsoch** [nextflow-io/rnatoy#1]
hey nextflow and @pditommaso! It gives me great joy to see your [recent post about using singularity](https://www.nextflow.io/blog/2016/more-fun-containers-hpc.html), and the integration with nextflow, which is something I was hoping for, and we've chat about before :)

![image](https://cloud.githubusercontent.com/assets/814322/21461490/cb7a3c5c-c906-11e6-8620-8fb38f603b48.png)

I am finishing up our registry for images, [Singularity Hub](http://www.singularity-hub.org), and part of that is going to be deploying singularity containers on several cloud providers (and local HPC clusters). The most basic use case is pulling and running one image, which was my plan, but I saw the nice comparison in your post above, and thought it would be really great to try and reproduce those pipelines in these locations, using singularity hub to obtain the images, and nextflow to hook things up. This will also be a good chance for me to get familiar with nextflow - and if it's a nice solution for workflows, I would implement a functionality in singularity hub for users to pull a spec to run with nextflow.

If this sounds like a good collaboration, are you able to share the workflows and benchmark utils that you used for your write up? If it's easy to use and intuitive, I'd love for it to be an integrated way to make it easier to run reproducible workflows. Thanks!

**Comment by pditommaso** [comment]
Hi Vanessa, this sounds really interesting and I'm very happy to read that you are going to launch a Singularity hub!

To reproduce the RnaToy pipeline simply follow the steps in the project [readme](https://github.com/nextflow-io/rnatoy) which instructs you run it with Docker. 

To use Singularity, convert the [Docker image](https://github.com/nextflow-io/rnatoy/blob/master/nextflow.config#L6) to a Singularity image file, then create a file named `nextflow.config` in the launch directory, with the following content: 

```
singularity.enabled = true
singularity.autoMounts = true
process.container = 'image-file-path'
```

and run it with this command: 

```
nextflow run nextflow-io/rnatoy
```

Feel free to contact me on [Gitter](https://gitter.im/pditommaso) for any problem.

**Comment by vsoch** [comment]
sweet! I will give this a try - thanks for your prompt response and happy holidays!

**Comment by pditommaso** [comment]
Same there!

**Comment by pditommaso** [comment]
Hi @vsoch, any progress on this? Don't hesitate to contact me for any problem. I would love to see these workflows included in the Singularity Hub.

**Comment by vsoch** [comment]
Hey @pditommaso ! HUGE progress on Singularity Hub over this break - I'm about to put in a big set of changes too. I'm going to hold back on implementing a particular pipeline at this point, per another developer pointing out that there are tens and tens of them. You can definitely close the issue, I'll ping again if/when necessary. Thanks for checking up on this!

**Comment by pditommaso** [comment]
👍
