### ISSUE TITLE
AWS: fatal error: Unable to locate credentials

### ISSUE THREAD

**Issue by stevekm** [nextflow-io/rnatoy#3]
I am trying to following the guide here:
https://github.com/nextflow-io/rnatoy/tree/peerj5515

but the data sync step is failing:

```bash
$ aws s3 sync s3://cbcrg-eu/rnatoy-mouse/ data
fatal error: Unable to locate credentials
```
Is this still needed? And if so, is there another dataset loaded elsewhere?

**Comment by pditommaso** [comment]
The error message is clear *fatal error: Unable to locate credentials*. You need AWS credentials event to access public data.
